<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BLLGOPALREDDY" failures="1" tests="3" name="com.advaita.EndtoEnd.run.test.DataSetUpEndToEnd" time="105.532" errors="0" timestamp="2024-09-09T13:28:01 IST" skipped="0">
  <testcase classname="com.advaita.EndtoEnd.run.test.DataSetUpEndToEnd" name="verifyAutoGenerateQuestionCreateNewDatasetWithSpecifyingType" time="64.677"/>
  <system-out/>
  <testcase classname="com.advaita.EndtoEnd.run.test.DataSetUpEndToEnd" name="verifynewCreateMetaData" time="20.194">
    <failure message="edit button is displayed. expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: edit button is displayed. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at com.advaita.DataSetUp.PageObject.MetaData.verifyExecuteUpadtedMetaData(MetaData.java:899)
at com.advaita.EndtoEnd.run.test.DataSetUpEndToEnd.verifynewCreateMetaData(DataSetUpEndToEnd.java:110)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifynewCreateMetaData -->
  <system-out/>
  <testcase classname="com.advaita.EndtoEnd.run.test.DataSetUpEndToEnd" name="verifyCreateManualUpload" time="20.661"/>
  <system-out/>
</testsuite> <!-- com.advaita.EndtoEnd.run.test.DataSetUpEndToEnd -->
